// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using GrpcApi.Infrastructure.Persistance;

namespace GrpcApi.Infrastructure.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("GrpcApi.Application.Entities.OtherThing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_other_things");

                    b.ToTable("other_things");
                });

            modelBuilder.Entity("GrpcApi.Application.Entities.Something", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("OtherThingId")
                        .HasColumnType("uuid")
                        .HasColumnName("other_thing_id");

                    b.HasKey("Id")
                        .HasName("pk_somethings");

                    b.HasIndex("OtherThingId")
                        .HasDatabaseName("ix_somethings_other_thing_id");

                    b.ToTable("somethings");
                });

            modelBuilder.Entity("GrpcApi.Application.Entities.Something", b =>
                {
                    b.HasOne("GrpcApi.Application.Entities.OtherThing", "OtherThing")
                        .WithMany()
                        .HasForeignKey("OtherThingId")
                        .HasConstraintName("fk_somethings_other_things_other_thing_id");

                    b.Navigation("OtherThing");
                });
#pragma warning restore 612, 618
        }
    }
}
